"""
muttdev setup - Initialize local development environment

This command helps developers set up their local MUTT development environment
by checking dependencies, creating config files, and starting services.
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path
from typing import Dict, List, Tuple


def register(subparsers):
    """Register the setup command with argparse."""
    parser = subparsers.add_parser(
        'setup',
        help='Initialize local development environment',
        description='Set up MUTT development environment with all dependencies'
    )

    parser.add_argument(
        '--skip-deps',
        action='store_true',
        help='Skip dependency checks'
    )

    parser.add_argument(
        '--skip-services',
        action='store_true',
        help='Skip starting services'
    )

    parser.add_argument(
        '--env',
        choices=['dev', 'test', 'prod'],
        default='dev',
        help='Environment to set up (default: dev)'
    )


def execute(args) -> int:
    """Execute the setup command."""
    print("=" * 70)
    print("MUTT v2.5 Development Environment Setup")
    print("=" * 70)
    print()

    # Determine project root
    project_root = Path(__file__).parent.parent.parent
    os.chdir(project_root)

    print(f"Project root: {project_root}")
    print(f"Environment: {args.env}")
    print()

    # Step 1: Check dependencies
    if not args.skip_deps:
        print("[1/5] Checking dependencies...")
        if not check_dependencies():
            return 1
        print("✓ All dependencies found\n")
    else:
        print("[1/5] Skipping dependency checks\n")

    # Step 2: Create environment file
    print("[2/5] Creating .env file...")
    if create_env_file(args.env):
        print("✓ .env file created\n")
    else:
        print("⚠ .env file already exists, skipping\n")

    # Step 3: Initialize Redis defaults
    print("[3/5] Initializing Redis with default configs...")
    init_redis_defaults()

    # Step 4: Set up database
    print("[4/5] Setting up PostgreSQL database...")
    setup_database()

    # Step 5: Start services
    if not args.skip_services:
        print("[5/5] Starting MUTT services...")
        start_services()
    else:
        print("[5/5] Skipping service startup\n")

    print("=" * 70)
    print("✓ Setup complete!")
    print("=" * 70)
    print()
    print("Next steps:")
    print("  1. Review and update .env file with your settings")
    print("  2. Run 'muttdev status' to check service health")
    print("  3. Run 'muttdev logs <service>' to view logs")
    print("  4. Run 'muttdev test' to run the test suite")
    print()

    return 0


def check_dependencies() -> bool:
    """Check that required dependencies are installed."""
    required = {
        'python3': 'Python 3.8+',
        'docker': 'Docker',
        'docker-compose': 'Docker Compose',
        'redis-cli': 'Redis CLI',
        'psql': 'PostgreSQL Client'
    }

    missing = []

    for cmd, name in required.items():
        if not shutil.which(cmd):
            print(f"  ✗ {name} not found ({cmd})")
            missing.append(name)
        else:
            print(f"  ✓ {name} found")

    if missing:
        print()
        print(f"Error: Missing required dependencies: {', '.join(missing)}")
        print()
        print("Installation instructions:")
        print("  macOS:   brew install python docker redis postgresql")
        print("  Ubuntu:  sudo apt install python3 docker.io redis-tools postgresql-client")
        print("  Windows: Use WSL2 or install via package managers")
        return False

    return True


def create_env_file(env: str) -> bool:
    """Create .env file from template."""
    env_file = Path('.env')

    if env_file.exists():
        return False

    template = f"""# MUTT v2.5 Environment Configuration
# Generated by: muttdev setup --env={env}

# Environment
ENV={env}

# Redis Configuration
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_TLS_ENABLED=false
REDIS_MAX_CONNECTIONS=10

# PostgreSQL Configuration
DB_HOST=localhost
DB_PORT=5432
DB_NAME=mutt
DB_USER=mutt_app
DB_POOL_MIN_CONN=2
DB_POOL_MAX_CONN=10
DB_TLS_ENABLED=false

# Vault Configuration
VAULT_ADDR=http://localhost:8200
VAULT_TOKEN=dev-token-123
VAULT_SECRET_PATH=secret/mutt/{env}

# Service Ports
INGESTOR_PORT=8080
ALERTER_PORT=8082
MOOG_FORWARDER_PORT=8084
WEBUI_PORT=8090
REMEDIATION_PORT=8086

# Metrics Ports
INGESTOR_METRICS_PORT=8081
ALERTER_METRICS_PORT=8083
MOOG_METRICS_PORT=8085
WEBUI_METRICS_PORT=8091
REMEDIATION_METRICS_PORT=8087

# Feature Flags
DYNAMIC_CONFIG_ENABLED=true
CIRCUIT_BREAKER_ENABLED=true
RATE_LIMIT_ENABLED=true
DISTRIBUTED_TRACING_ENABLED=false

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json

# Retention Policies
EVENT_RETENTION_DAYS=90
EVENT_ARCHIVE_RETENTION_YEARS=7
CONFIG_AUDIT_RETENTION_DAYS=365
"""

    env_file.write_text(template)
    return True


def init_redis_defaults():
    """Initialize Redis with default configuration values."""
    try:
        result = subprocess.run(
            ['python3', 'scripts/init_default_configs.py'],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            print("✓ Redis defaults initialized")
        else:
            print(f"⚠ Redis init had warnings: {result.stderr}")
    except Exception as e:
        print(f"⚠ Could not initialize Redis defaults: {e}")
    print()


def setup_database():
    """Set up PostgreSQL database schema."""
    try:
        # Check if database exists
        result = subprocess.run(
            ['psql', '-h', 'localhost', '-U', 'postgres', '-lqt'],
            capture_output=True,
            text=True
        )

        if 'mutt' not in result.stdout:
            print("  Creating database...")
            subprocess.run(
                ['psql', '-h', 'localhost', '-U', 'postgres', '-c', 'CREATE DATABASE mutt;'],
                check=True
            )

        print("  Applying schema...")
        subprocess.run(
            ['psql', '-h', 'localhost', '-U', 'postgres', '-d', 'mutt', '-f', 'database/postgres-init.sql'],
            check=True,
            capture_output=True
        )

        print("✓ Database set up successfully")

    except subprocess.CalledProcessError as e:
        print(f"⚠ Database setup had issues: {e}")
    except Exception as e:
        print(f"⚠ Could not set up database: {e}")

    print()


def start_services():
    """Start MUTT services using docker-compose."""
    try:
        if Path('docker-compose.yml').exists():
            print("  Starting services with docker-compose...")
            subprocess.run(
                ['docker-compose', 'up', '-d'],
                check=True
            )
            print("✓ Services started")
        else:
            print("  ⚠ docker-compose.yml not found, skipping service startup")

    except subprocess.CalledProcessError as e:
        print(f"  ⚠ Failed to start services: {e}")
    except Exception as e:
        print(f"  ⚠ Error starting services: {e}")

    print()
